{% set version = "2.2.2" %}

package:
  name: pandoc
  version: {{ version }}

source:
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb  # [linux64]
  sha256: 7d74d96f231960fde9a611803dd9b5047128d9f264062ec02c38c4a3dbf520e2  # [linux64]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-macOS.pkg  # [osx]
  sha256: a55c91f0bbb59246ac0ec841d68ac00b70e7e5a7af3f15c4fb25338fcfe1f0a7  # [osx]

  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows-x86_64.msi  # [win]
  sha256: d11f3e08156c0544417af6a44cb44af8e5c17c0475663bebc046d395de4916dd  # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.11  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://pandoc.org/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - jankatins
    - ocefpaf
    - dhimmel
