{% set version = "1.19.2" %}

package:
  name: pandoc
  version: {{ version }}

source:
  fn: pandoc-{{ version }}-amd64.deb                                                                     # [linux64]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-1-amd64.deb    # [linux64]
  sha256: 308fa08d427a2b49c6b4d1558884c8fad2f07684997232b4818b98cc7ca14392                               # [linux64]
  fn: pandoc-{{ version }}.pkg                                                                           # [osx]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-osx.pkg        # [osx]
  sha256: ebf8af76d94a87803d938e18d1b6f2da472e610a73f48838932a808ca2593239                               # [osx]
  fn: pandoc-{{ version }}-windows.msi                                                                   # [win]
  url: https://github.com/jgm/pandoc/releases/download/{{ version }}/pandoc-{{ version }}-windows.msi    # [win]
  sha256: 63d26519adc2a86f71160058b8a03f2a4911064ef4b4ae3d3900c413e81beac0                               # [win]

build:
   number: 0

requirements:
  run:
    - gmp  # [linux64]
    - zlib 1.2.*  # [linux64]

test:
  commands:
    - pandoc --help
    - pandoc --version

about:
  home: http://johnmacfarlane.net/pandoc/
  license: GPL-2.0
  summary: 'Universal markup converter (repackaged binaries).'

extra:
  recipe-maintainers:
    - janschulz
    - ocefpaf
